### ISSUE TITLE
Arduino remote

### ISSUE THREAD

**Issue by Vitalicus** [mungewell/openDR-Remote#2]
Can you help me on this project ?
http://www.tascamforums.com/threads/arduino-remote-dr-22wl.4605/

**Comment by mungewell** [comment]
Hi,
I'm happy to help, but prefer people to help themselves... python code it quite readable. :-) Been a long time since I was working on this project, but if you just want to start/stop recording/playback it should be simple.

It looks like you need to send this sequence when you connect:
https://github.com/mungewell/openDR-Remote/blob/master/openDR-Remote.py#L317

And then you can send a packet to signify each button presses:
https://github.com/mungewell/openDR-Remote/blob/master/openDR-Remote.py#L355

The majority of the code is decoding the continuous stream of data from the device, which signals which mode you are using, time stamps, VU meters, etc.

If you want to do more then I suggest download the python script (and 'Construct' module https://pypi.python.org/pypi/construct/2.8.12) and tinker to familiarize yourself. Script might need tweaking for Python3 print statements, but should run on Linux/Windows OK.

Cheers,
Simon.

**Comment by Vitalicus** [comment]
Tell me please .. how to send the code ? I want to test before from PC
...through Telnet is posible ? Sent text like this ?
\x44\x52\x20\x42\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00
Or any soft ?

2017-05-24 1:01 GMT+03:00 mungewell <notifications@github.com>:
